{ ... }: {
  boot.kernelParams = [ "zfs.zfs_arc_max=2147483648" ];
  disko.devices.disk.main.device = "/dev/disk/by-path/";
  networking.hostId = "00000000";
  services.openssh.ports = 22;

  imports = [
    ../../modules/optional/boot-loader/limine.nix
    ../../modules/optional/firewall.nix
    ../../modules/optional/kernels/xanmod.nix
    ../../modules/optional/virtualisation/podman.nix
    ../../modules/shared
    ./modules
    ./services
  ];

  users.users.root = {
    hashedPassword = "generated by mkpasswd";
    openssh.authorizedKeys.keys = [
      "ssh public key 1"
      "ssh public key 2"
      "ssh public key ..."
    ];
  };
}
